/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MembershipApplicationListApiResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MembershipApplicationListApiResource{}

// MembershipApplicationListApiResource struct for MembershipApplicationListApiResource
type MembershipApplicationListApiResource struct {
	Items []MembershipApplicationApiResource `json:"items,omitempty"`
	Links *MembershipApplicationListLinks `json:"_links,omitempty"`
}

// NewMembershipApplicationListApiResource instantiates a new MembershipApplicationListApiResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembershipApplicationListApiResource() *MembershipApplicationListApiResource {
	this := MembershipApplicationListApiResource{}
	return &this
}

// NewMembershipApplicationListApiResourceWithDefaults instantiates a new MembershipApplicationListApiResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipApplicationListApiResourceWithDefaults() *MembershipApplicationListApiResource {
	this := MembershipApplicationListApiResource{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MembershipApplicationListApiResource) GetItems() []MembershipApplicationApiResource {
	if o == nil {
		var ret []MembershipApplicationApiResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MembershipApplicationListApiResource) GetItemsOk() ([]MembershipApplicationApiResource, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *MembershipApplicationListApiResource) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []MembershipApplicationApiResource and assigns it to the Items field.
func (o *MembershipApplicationListApiResource) SetItems(v []MembershipApplicationApiResource) {
	o.Items = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *MembershipApplicationListApiResource) GetLinks() MembershipApplicationListLinks {
	if o == nil || IsNil(o.Links) {
		var ret MembershipApplicationListLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MembershipApplicationListApiResource) GetLinksOk() (*MembershipApplicationListLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *MembershipApplicationListApiResource) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given MembershipApplicationListLinks and assigns it to the Links field.
func (o *MembershipApplicationListApiResource) SetLinks(v MembershipApplicationListLinks) {
	o.Links = &v
}

func (o MembershipApplicationListApiResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MembershipApplicationListApiResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableMembershipApplicationListApiResource struct {
	value *MembershipApplicationListApiResource
	isSet bool
}

func (v NullableMembershipApplicationListApiResource) Get() *MembershipApplicationListApiResource {
	return v.value
}

func (v *NullableMembershipApplicationListApiResource) Set(val *MembershipApplicationListApiResource) {
	v.value = val
	v.isSet = true
}

func (v NullableMembershipApplicationListApiResource) IsSet() bool {
	return v.isSet
}

func (v *NullableMembershipApplicationListApiResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembershipApplicationListApiResource(val *MembershipApplicationListApiResource) *NullableMembershipApplicationListApiResource {
	return &NullableMembershipApplicationListApiResource{value: val, isSet: true}
}

func (v NullableMembershipApplicationListApiResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembershipApplicationListApiResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


