/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapabilityDetailsLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityDetailsLinks{}

// CapabilityDetailsLinks struct for CapabilityDetailsLinks
type CapabilityDetailsLinks struct {
	Self *ResourceLink `json:"self,omitempty"`
	Members *ResourceLink `json:"members,omitempty"`
	Clusters *ResourceLink `json:"clusters,omitempty"`
	MembershipApplications *ResourceLink `json:"membershipApplications,omitempty"`
	LeaveCapability *ResourceLink `json:"leaveCapability,omitempty"`
	AwsAccount *ResourceLink `json:"awsAccount,omitempty"`
	RequestCapabilityDeletion *ResourceLink `json:"requestCapabilityDeletion,omitempty"`
	CancelCapabilityDeletionRequest *ResourceLink `json:"cancelCapabilityDeletionRequest,omitempty"`
	Metadata *ResourceLink `json:"metadata,omitempty"`
	SetRequiredMetadata *ResourceLink `json:"setRequiredMetadata,omitempty"`
	GetLinkedTeams *ResourceLink `json:"getLinkedTeams,omitempty"`
	JoinCapability *ResourceLink `json:"joinCapability,omitempty"`
	SendInvitations *ResourceLink `json:"sendInvitations,omitempty"`
	ConfigurationLevel *ResourceLink `json:"configurationLevel,omitempty"`
}

// NewCapabilityDetailsLinks instantiates a new CapabilityDetailsLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityDetailsLinks() *CapabilityDetailsLinks {
	this := CapabilityDetailsLinks{}
	return &this
}

// NewCapabilityDetailsLinksWithDefaults instantiates a new CapabilityDetailsLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityDetailsLinksWithDefaults() *CapabilityDetailsLinks {
	this := CapabilityDetailsLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetSelf() ResourceLink {
	if o == nil || IsNil(o.Self) {
		var ret ResourceLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetSelfOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ResourceLink and assigns it to the Self field.
func (o *CapabilityDetailsLinks) SetSelf(v ResourceLink) {
	o.Self = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetMembers() ResourceLink {
	if o == nil || IsNil(o.Members) {
		var ret ResourceLink
		return ret
	}
	return *o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetMembersOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given ResourceLink and assigns it to the Members field.
func (o *CapabilityDetailsLinks) SetMembers(v ResourceLink) {
	o.Members = &v
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetClusters() ResourceLink {
	if o == nil || IsNil(o.Clusters) {
		var ret ResourceLink
		return ret
	}
	return *o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetClustersOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Clusters) {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasClusters() bool {
	if o != nil && !IsNil(o.Clusters) {
		return true
	}

	return false
}

// SetClusters gets a reference to the given ResourceLink and assigns it to the Clusters field.
func (o *CapabilityDetailsLinks) SetClusters(v ResourceLink) {
	o.Clusters = &v
}

// GetMembershipApplications returns the MembershipApplications field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetMembershipApplications() ResourceLink {
	if o == nil || IsNil(o.MembershipApplications) {
		var ret ResourceLink
		return ret
	}
	return *o.MembershipApplications
}

// GetMembershipApplicationsOk returns a tuple with the MembershipApplications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetMembershipApplicationsOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.MembershipApplications) {
		return nil, false
	}
	return o.MembershipApplications, true
}

// HasMembershipApplications returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasMembershipApplications() bool {
	if o != nil && !IsNil(o.MembershipApplications) {
		return true
	}

	return false
}

// SetMembershipApplications gets a reference to the given ResourceLink and assigns it to the MembershipApplications field.
func (o *CapabilityDetailsLinks) SetMembershipApplications(v ResourceLink) {
	o.MembershipApplications = &v
}

// GetLeaveCapability returns the LeaveCapability field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetLeaveCapability() ResourceLink {
	if o == nil || IsNil(o.LeaveCapability) {
		var ret ResourceLink
		return ret
	}
	return *o.LeaveCapability
}

// GetLeaveCapabilityOk returns a tuple with the LeaveCapability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetLeaveCapabilityOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.LeaveCapability) {
		return nil, false
	}
	return o.LeaveCapability, true
}

// HasLeaveCapability returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasLeaveCapability() bool {
	if o != nil && !IsNil(o.LeaveCapability) {
		return true
	}

	return false
}

// SetLeaveCapability gets a reference to the given ResourceLink and assigns it to the LeaveCapability field.
func (o *CapabilityDetailsLinks) SetLeaveCapability(v ResourceLink) {
	o.LeaveCapability = &v
}

// GetAwsAccount returns the AwsAccount field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetAwsAccount() ResourceLink {
	if o == nil || IsNil(o.AwsAccount) {
		var ret ResourceLink
		return ret
	}
	return *o.AwsAccount
}

// GetAwsAccountOk returns a tuple with the AwsAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetAwsAccountOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.AwsAccount) {
		return nil, false
	}
	return o.AwsAccount, true
}

// HasAwsAccount returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasAwsAccount() bool {
	if o != nil && !IsNil(o.AwsAccount) {
		return true
	}

	return false
}

// SetAwsAccount gets a reference to the given ResourceLink and assigns it to the AwsAccount field.
func (o *CapabilityDetailsLinks) SetAwsAccount(v ResourceLink) {
	o.AwsAccount = &v
}

// GetRequestCapabilityDeletion returns the RequestCapabilityDeletion field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetRequestCapabilityDeletion() ResourceLink {
	if o == nil || IsNil(o.RequestCapabilityDeletion) {
		var ret ResourceLink
		return ret
	}
	return *o.RequestCapabilityDeletion
}

// GetRequestCapabilityDeletionOk returns a tuple with the RequestCapabilityDeletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetRequestCapabilityDeletionOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.RequestCapabilityDeletion) {
		return nil, false
	}
	return o.RequestCapabilityDeletion, true
}

// HasRequestCapabilityDeletion returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasRequestCapabilityDeletion() bool {
	if o != nil && !IsNil(o.RequestCapabilityDeletion) {
		return true
	}

	return false
}

// SetRequestCapabilityDeletion gets a reference to the given ResourceLink and assigns it to the RequestCapabilityDeletion field.
func (o *CapabilityDetailsLinks) SetRequestCapabilityDeletion(v ResourceLink) {
	o.RequestCapabilityDeletion = &v
}

// GetCancelCapabilityDeletionRequest returns the CancelCapabilityDeletionRequest field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetCancelCapabilityDeletionRequest() ResourceLink {
	if o == nil || IsNil(o.CancelCapabilityDeletionRequest) {
		var ret ResourceLink
		return ret
	}
	return *o.CancelCapabilityDeletionRequest
}

// GetCancelCapabilityDeletionRequestOk returns a tuple with the CancelCapabilityDeletionRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetCancelCapabilityDeletionRequestOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.CancelCapabilityDeletionRequest) {
		return nil, false
	}
	return o.CancelCapabilityDeletionRequest, true
}

// HasCancelCapabilityDeletionRequest returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasCancelCapabilityDeletionRequest() bool {
	if o != nil && !IsNil(o.CancelCapabilityDeletionRequest) {
		return true
	}

	return false
}

// SetCancelCapabilityDeletionRequest gets a reference to the given ResourceLink and assigns it to the CancelCapabilityDeletionRequest field.
func (o *CapabilityDetailsLinks) SetCancelCapabilityDeletionRequest(v ResourceLink) {
	o.CancelCapabilityDeletionRequest = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetMetadata() ResourceLink {
	if o == nil || IsNil(o.Metadata) {
		var ret ResourceLink
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetMetadataOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ResourceLink and assigns it to the Metadata field.
func (o *CapabilityDetailsLinks) SetMetadata(v ResourceLink) {
	o.Metadata = &v
}

// GetSetRequiredMetadata returns the SetRequiredMetadata field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetSetRequiredMetadata() ResourceLink {
	if o == nil || IsNil(o.SetRequiredMetadata) {
		var ret ResourceLink
		return ret
	}
	return *o.SetRequiredMetadata
}

// GetSetRequiredMetadataOk returns a tuple with the SetRequiredMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetSetRequiredMetadataOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.SetRequiredMetadata) {
		return nil, false
	}
	return o.SetRequiredMetadata, true
}

// HasSetRequiredMetadata returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasSetRequiredMetadata() bool {
	if o != nil && !IsNil(o.SetRequiredMetadata) {
		return true
	}

	return false
}

// SetSetRequiredMetadata gets a reference to the given ResourceLink and assigns it to the SetRequiredMetadata field.
func (o *CapabilityDetailsLinks) SetSetRequiredMetadata(v ResourceLink) {
	o.SetRequiredMetadata = &v
}

// GetGetLinkedTeams returns the GetLinkedTeams field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetGetLinkedTeams() ResourceLink {
	if o == nil || IsNil(o.GetLinkedTeams) {
		var ret ResourceLink
		return ret
	}
	return *o.GetLinkedTeams
}

// GetGetLinkedTeamsOk returns a tuple with the GetLinkedTeams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetGetLinkedTeamsOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.GetLinkedTeams) {
		return nil, false
	}
	return o.GetLinkedTeams, true
}

// HasGetLinkedTeams returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasGetLinkedTeams() bool {
	if o != nil && !IsNil(o.GetLinkedTeams) {
		return true
	}

	return false
}

// SetGetLinkedTeams gets a reference to the given ResourceLink and assigns it to the GetLinkedTeams field.
func (o *CapabilityDetailsLinks) SetGetLinkedTeams(v ResourceLink) {
	o.GetLinkedTeams = &v
}

// GetJoinCapability returns the JoinCapability field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetJoinCapability() ResourceLink {
	if o == nil || IsNil(o.JoinCapability) {
		var ret ResourceLink
		return ret
	}
	return *o.JoinCapability
}

// GetJoinCapabilityOk returns a tuple with the JoinCapability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetJoinCapabilityOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.JoinCapability) {
		return nil, false
	}
	return o.JoinCapability, true
}

// HasJoinCapability returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasJoinCapability() bool {
	if o != nil && !IsNil(o.JoinCapability) {
		return true
	}

	return false
}

// SetJoinCapability gets a reference to the given ResourceLink and assigns it to the JoinCapability field.
func (o *CapabilityDetailsLinks) SetJoinCapability(v ResourceLink) {
	o.JoinCapability = &v
}

// GetSendInvitations returns the SendInvitations field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetSendInvitations() ResourceLink {
	if o == nil || IsNil(o.SendInvitations) {
		var ret ResourceLink
		return ret
	}
	return *o.SendInvitations
}

// GetSendInvitationsOk returns a tuple with the SendInvitations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetSendInvitationsOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.SendInvitations) {
		return nil, false
	}
	return o.SendInvitations, true
}

// HasSendInvitations returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasSendInvitations() bool {
	if o != nil && !IsNil(o.SendInvitations) {
		return true
	}

	return false
}

// SetSendInvitations gets a reference to the given ResourceLink and assigns it to the SendInvitations field.
func (o *CapabilityDetailsLinks) SetSendInvitations(v ResourceLink) {
	o.SendInvitations = &v
}

// GetConfigurationLevel returns the ConfigurationLevel field value if set, zero value otherwise.
func (o *CapabilityDetailsLinks) GetConfigurationLevel() ResourceLink {
	if o == nil || IsNil(o.ConfigurationLevel) {
		var ret ResourceLink
		return ret
	}
	return *o.ConfigurationLevel
}

// GetConfigurationLevelOk returns a tuple with the ConfigurationLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityDetailsLinks) GetConfigurationLevelOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.ConfigurationLevel) {
		return nil, false
	}
	return o.ConfigurationLevel, true
}

// HasConfigurationLevel returns a boolean if a field has been set.
func (o *CapabilityDetailsLinks) HasConfigurationLevel() bool {
	if o != nil && !IsNil(o.ConfigurationLevel) {
		return true
	}

	return false
}

// SetConfigurationLevel gets a reference to the given ResourceLink and assigns it to the ConfigurationLevel field.
func (o *CapabilityDetailsLinks) SetConfigurationLevel(v ResourceLink) {
	o.ConfigurationLevel = &v
}

func (o CapabilityDetailsLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityDetailsLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.Clusters) {
		toSerialize["clusters"] = o.Clusters
	}
	if !IsNil(o.MembershipApplications) {
		toSerialize["membershipApplications"] = o.MembershipApplications
	}
	if !IsNil(o.LeaveCapability) {
		toSerialize["leaveCapability"] = o.LeaveCapability
	}
	if !IsNil(o.AwsAccount) {
		toSerialize["awsAccount"] = o.AwsAccount
	}
	if !IsNil(o.RequestCapabilityDeletion) {
		toSerialize["requestCapabilityDeletion"] = o.RequestCapabilityDeletion
	}
	if !IsNil(o.CancelCapabilityDeletionRequest) {
		toSerialize["cancelCapabilityDeletionRequest"] = o.CancelCapabilityDeletionRequest
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.SetRequiredMetadata) {
		toSerialize["setRequiredMetadata"] = o.SetRequiredMetadata
	}
	if !IsNil(o.GetLinkedTeams) {
		toSerialize["getLinkedTeams"] = o.GetLinkedTeams
	}
	if !IsNil(o.JoinCapability) {
		toSerialize["joinCapability"] = o.JoinCapability
	}
	if !IsNil(o.SendInvitations) {
		toSerialize["sendInvitations"] = o.SendInvitations
	}
	if !IsNil(o.ConfigurationLevel) {
		toSerialize["configurationLevel"] = o.ConfigurationLevel
	}
	return toSerialize, nil
}

type NullableCapabilityDetailsLinks struct {
	value *CapabilityDetailsLinks
	isSet bool
}

func (v NullableCapabilityDetailsLinks) Get() *CapabilityDetailsLinks {
	return v.value
}

func (v *NullableCapabilityDetailsLinks) Set(val *CapabilityDetailsLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityDetailsLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityDetailsLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityDetailsLinks(val *CapabilityDetailsLinks) *NullableCapabilityDetailsLinks {
	return &NullableCapabilityDetailsLinks{value: val, isSet: true}
}

func (v NullableCapabilityDetailsLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityDetailsLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


