/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InvitationsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvitationsRequest{}

// InvitationsRequest struct for InvitationsRequest
type InvitationsRequest struct {
	Invitees []string `json:"invitees"`
}

type _InvitationsRequest InvitationsRequest

// NewInvitationsRequest instantiates a new InvitationsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationsRequest(invitees []string) *InvitationsRequest {
	this := InvitationsRequest{}
	this.Invitees = invitees
	return &this
}

// NewInvitationsRequestWithDefaults instantiates a new InvitationsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationsRequestWithDefaults() *InvitationsRequest {
	this := InvitationsRequest{}
	return &this
}

// GetInvitees returns the Invitees field value
func (o *InvitationsRequest) GetInvitees() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Invitees
}

// GetInviteesOk returns a tuple with the Invitees field value
// and a boolean to check if the value has been set.
func (o *InvitationsRequest) GetInviteesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Invitees, true
}

// SetInvitees sets field value
func (o *InvitationsRequest) SetInvitees(v []string) {
	o.Invitees = v
}

func (o InvitationsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvitationsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invitees"] = o.Invitees
	return toSerialize, nil
}

func (o *InvitationsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invitees",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvitationsRequest := _InvitationsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvitationsRequest)

	if err != nil {
		return err
	}

	*o = InvitationsRequest(varInvitationsRequest)

	return err
}

type NullableInvitationsRequest struct {
	value *InvitationsRequest
	isSet bool
}

func (v NullableInvitationsRequest) Get() *InvitationsRequest {
	return v.value
}

func (v *NullableInvitationsRequest) Set(val *InvitationsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationsRequest(val *InvitationsRequest) *NullableInvitationsRequest {
	return &NullableInvitationsRequest{value: val, isSet: true}
}

func (v NullableInvitationsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


