/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewECRRepositoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewECRRepositoryRequest{}

// NewECRRepositoryRequest struct for NewECRRepositoryRequest
type NewECRRepositoryRequest struct {
	Name string `json:"name"`
	Description string `json:"description"`
}

type _NewECRRepositoryRequest NewECRRepositoryRequest

// NewNewECRRepositoryRequest instantiates a new NewECRRepositoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewECRRepositoryRequest(name string, description string) *NewECRRepositoryRequest {
	this := NewECRRepositoryRequest{}
	this.Name = name
	this.Description = description
	return &this
}

// NewNewECRRepositoryRequestWithDefaults instantiates a new NewECRRepositoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewECRRepositoryRequestWithDefaults() *NewECRRepositoryRequest {
	this := NewECRRepositoryRequest{}
	return &this
}

// GetName returns the Name field value
func (o *NewECRRepositoryRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewECRRepositoryRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewECRRepositoryRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *NewECRRepositoryRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NewECRRepositoryRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NewECRRepositoryRequest) SetDescription(v string) {
	o.Description = v
}

func (o NewECRRepositoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewECRRepositoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *NewECRRepositoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewECRRepositoryRequest := _NewECRRepositoryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewECRRepositoryRequest)

	if err != nil {
		return err
	}

	*o = NewECRRepositoryRequest(varNewECRRepositoryRequest)

	return err
}

type NullableNewECRRepositoryRequest struct {
	value *NewECRRepositoryRequest
	isSet bool
}

func (v NullableNewECRRepositoryRequest) Get() *NewECRRepositoryRequest {
	return v.value
}

func (v *NullableNewECRRepositoryRequest) Set(val *NewECRRepositoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNewECRRepositoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNewECRRepositoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewECRRepositoryRequest(val *NewECRRepositoryRequest) *NullableNewECRRepositoryRequest {
	return &NullableNewECRRepositoryRequest{value: val, isSet: true}
}

func (v NullableNewECRRepositoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewECRRepositoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


