/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidateMessageContractRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateMessageContractRequest{}

// ValidateMessageContractRequest struct for ValidateMessageContractRequest
type ValidateMessageContractRequest struct {
	MessageType string `json:"messageType"`
	Schema string `json:"schema"`
}

type _ValidateMessageContractRequest ValidateMessageContractRequest

// NewValidateMessageContractRequest instantiates a new ValidateMessageContractRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateMessageContractRequest(messageType string, schema string) *ValidateMessageContractRequest {
	this := ValidateMessageContractRequest{}
	this.MessageType = messageType
	this.Schema = schema
	return &this
}

// NewValidateMessageContractRequestWithDefaults instantiates a new ValidateMessageContractRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateMessageContractRequestWithDefaults() *ValidateMessageContractRequest {
	this := ValidateMessageContractRequest{}
	return &this
}

// GetMessageType returns the MessageType field value
func (o *ValidateMessageContractRequest) GetMessageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value
// and a boolean to check if the value has been set.
func (o *ValidateMessageContractRequest) GetMessageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageType, true
}

// SetMessageType sets field value
func (o *ValidateMessageContractRequest) SetMessageType(v string) {
	o.MessageType = v
}

// GetSchema returns the Schema field value
func (o *ValidateMessageContractRequest) GetSchema() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *ValidateMessageContractRequest) GetSchemaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *ValidateMessageContractRequest) SetSchema(v string) {
	o.Schema = v
}

func (o ValidateMessageContractRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateMessageContractRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageType"] = o.MessageType
	toSerialize["schema"] = o.Schema
	return toSerialize, nil
}

func (o *ValidateMessageContractRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageType",
		"schema",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateMessageContractRequest := _ValidateMessageContractRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateMessageContractRequest)

	if err != nil {
		return err
	}

	*o = ValidateMessageContractRequest(varValidateMessageContractRequest)

	return err
}

type NullableValidateMessageContractRequest struct {
	value *ValidateMessageContractRequest
	isSet bool
}

func (v NullableValidateMessageContractRequest) Get() *ValidateMessageContractRequest {
	return v.value
}

func (v *NullableValidateMessageContractRequest) Set(val *ValidateMessageContractRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateMessageContractRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateMessageContractRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateMessageContractRequest(val *ValidateMessageContractRequest) *NullableValidateMessageContractRequest {
	return &NullableValidateMessageContractRequest{value: val, isSet: true}
}

func (v NullableValidateMessageContractRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateMessageContractRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


