/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapabilityListApiResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityListApiResource{}

// CapabilityListApiResource struct for CapabilityListApiResource
type CapabilityListApiResource struct {
	Items []CapabilityListItemApiResource `json:"items,omitempty"`
	Links *CapabilityListLinks `json:"_links,omitempty"`
}

// NewCapabilityListApiResource instantiates a new CapabilityListApiResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityListApiResource() *CapabilityListApiResource {
	this := CapabilityListApiResource{}
	return &this
}

// NewCapabilityListApiResourceWithDefaults instantiates a new CapabilityListApiResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityListApiResourceWithDefaults() *CapabilityListApiResource {
	this := CapabilityListApiResource{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListApiResource) GetItems() []CapabilityListItemApiResource {
	if o == nil {
		var ret []CapabilityListItemApiResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListApiResource) GetItemsOk() ([]CapabilityListItemApiResource, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CapabilityListApiResource) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CapabilityListItemApiResource and assigns it to the Items field.
func (o *CapabilityListApiResource) SetItems(v []CapabilityListItemApiResource) {
	o.Items = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CapabilityListApiResource) GetLinks() CapabilityListLinks {
	if o == nil || IsNil(o.Links) {
		var ret CapabilityListLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityListApiResource) GetLinksOk() (*CapabilityListLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CapabilityListApiResource) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CapabilityListLinks and assigns it to the Links field.
func (o *CapabilityListApiResource) SetLinks(v CapabilityListLinks) {
	o.Links = &v
}

func (o CapabilityListApiResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityListApiResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCapabilityListApiResource struct {
	value *CapabilityListApiResource
	isSet bool
}

func (v NullableCapabilityListApiResource) Get() *CapabilityListApiResource {
	return v.value
}

func (v *NullableCapabilityListApiResource) Set(val *CapabilityListApiResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityListApiResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityListApiResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityListApiResource(val *CapabilityListApiResource) *NullableCapabilityListApiResource {
	return &NullableCapabilityListApiResource{value: val, isSet: true}
}

func (v NullableCapabilityListApiResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityListApiResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


