/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapabilityMembersLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityMembersLinks{}

// CapabilityMembersLinks struct for CapabilityMembersLinks
type CapabilityMembersLinks struct {
	Self *ResourceLink `json:"self,omitempty"`
}

// NewCapabilityMembersLinks instantiates a new CapabilityMembersLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityMembersLinks() *CapabilityMembersLinks {
	this := CapabilityMembersLinks{}
	return &this
}

// NewCapabilityMembersLinksWithDefaults instantiates a new CapabilityMembersLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityMembersLinksWithDefaults() *CapabilityMembersLinks {
	this := CapabilityMembersLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *CapabilityMembersLinks) GetSelf() ResourceLink {
	if o == nil || IsNil(o.Self) {
		var ret ResourceLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityMembersLinks) GetSelfOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *CapabilityMembersLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ResourceLink and assigns it to the Self field.
func (o *CapabilityMembersLinks) SetSelf(v ResourceLink) {
	o.Self = &v
}

func (o CapabilityMembersLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityMembersLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableCapabilityMembersLinks struct {
	value *CapabilityMembersLinks
	isSet bool
}

func (v NullableCapabilityMembersLinks) Get() *CapabilityMembersLinks {
	return v.value
}

func (v *NullableCapabilityMembersLinks) Set(val *CapabilityMembersLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityMembersLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityMembersLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityMembersLinks(val *CapabilityMembersLinks) *NullableCapabilityMembersLinks {
	return &NullableCapabilityMembersLinks{value: val, isSet: true}
}

func (v NullableCapabilityMembersLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityMembersLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


