/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AwsAccountLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsAccountLinks{}

// AwsAccountLinks struct for AwsAccountLinks
type AwsAccountLinks struct {
	Self *ResourceLink `json:"self,omitempty"`
}

// NewAwsAccountLinks instantiates a new AwsAccountLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsAccountLinks() *AwsAccountLinks {
	this := AwsAccountLinks{}
	return &this
}

// NewAwsAccountLinksWithDefaults instantiates a new AwsAccountLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsAccountLinksWithDefaults() *AwsAccountLinks {
	this := AwsAccountLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *AwsAccountLinks) GetSelf() ResourceLink {
	if o == nil || IsNil(o.Self) {
		var ret ResourceLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsAccountLinks) GetSelfOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *AwsAccountLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ResourceLink and assigns it to the Self field.
func (o *AwsAccountLinks) SetSelf(v ResourceLink) {
	o.Self = &v
}

func (o AwsAccountLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsAccountLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableAwsAccountLinks struct {
	value *AwsAccountLinks
	isSet bool
}

func (v NullableAwsAccountLinks) Get() *AwsAccountLinks {
	return v.value
}

func (v *NullableAwsAccountLinks) Set(val *AwsAccountLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsAccountLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsAccountLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsAccountLinks(val *AwsAccountLinks) *NullableAwsAccountLinks {
	return &NullableAwsAccountLinks{value: val, isSet: true}
}

func (v NullableAwsAccountLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsAccountLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


