/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaClusterListLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaClusterListLinks{}

// KafkaClusterListLinks struct for KafkaClusterListLinks
type KafkaClusterListLinks struct {
	Self *ResourceLink `json:"self,omitempty"`
}

// NewKafkaClusterListLinks instantiates a new KafkaClusterListLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaClusterListLinks() *KafkaClusterListLinks {
	this := KafkaClusterListLinks{}
	return &this
}

// NewKafkaClusterListLinksWithDefaults instantiates a new KafkaClusterListLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaClusterListLinksWithDefaults() *KafkaClusterListLinks {
	this := KafkaClusterListLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *KafkaClusterListLinks) GetSelf() ResourceLink {
	if o == nil || IsNil(o.Self) {
		var ret ResourceLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaClusterListLinks) GetSelfOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *KafkaClusterListLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ResourceLink and assigns it to the Self field.
func (o *KafkaClusterListLinks) SetSelf(v ResourceLink) {
	o.Self = &v
}

func (o KafkaClusterListLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaClusterListLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableKafkaClusterListLinks struct {
	value *KafkaClusterListLinks
	isSet bool
}

func (v NullableKafkaClusterListLinks) Get() *KafkaClusterListLinks {
	return v.value
}

func (v *NullableKafkaClusterListLinks) Set(val *KafkaClusterListLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaClusterListLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaClusterListLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaClusterListLinks(val *KafkaClusterListLinks) *NullableKafkaClusterListLinks {
	return &NullableKafkaClusterListLinks{value: val, isSet: true}
}

func (v NullableKafkaClusterListLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaClusterListLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


