/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdatePersonalInformationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePersonalInformationRequest{}

// UpdatePersonalInformationRequest struct for UpdatePersonalInformationRequest
type UpdatePersonalInformationRequest struct {
	Name NullableString `json:"name,omitempty"`
	Email NullableString `json:"email,omitempty"`
}

// NewUpdatePersonalInformationRequest instantiates a new UpdatePersonalInformationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePersonalInformationRequest() *UpdatePersonalInformationRequest {
	this := UpdatePersonalInformationRequest{}
	return &this
}

// NewUpdatePersonalInformationRequestWithDefaults instantiates a new UpdatePersonalInformationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePersonalInformationRequestWithDefaults() *UpdatePersonalInformationRequest {
	this := UpdatePersonalInformationRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePersonalInformationRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePersonalInformationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdatePersonalInformationRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdatePersonalInformationRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdatePersonalInformationRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdatePersonalInformationRequest) UnsetName() {
	o.Name.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdatePersonalInformationRequest) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdatePersonalInformationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *UpdatePersonalInformationRequest) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *UpdatePersonalInformationRequest) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *UpdatePersonalInformationRequest) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *UpdatePersonalInformationRequest) UnsetEmail() {
	o.Email.Unset()
}

func (o UpdatePersonalInformationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePersonalInformationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return toSerialize, nil
}

type NullableUpdatePersonalInformationRequest struct {
	value *UpdatePersonalInformationRequest
	isSet bool
}

func (v NullableUpdatePersonalInformationRequest) Get() *UpdatePersonalInformationRequest {
	return v.value
}

func (v *NullableUpdatePersonalInformationRequest) Set(val *UpdatePersonalInformationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePersonalInformationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePersonalInformationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePersonalInformationRequest(val *UpdatePersonalInformationRequest) *NullableUpdatePersonalInformationRequest {
	return &NullableUpdatePersonalInformationRequest{value: val, isSet: true}
}

func (v NullableUpdatePersonalInformationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePersonalInformationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


