/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaClusterListApiResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaClusterListApiResource{}

// KafkaClusterListApiResource struct for KafkaClusterListApiResource
type KafkaClusterListApiResource struct {
	Items []KafkaClusterApiResource `json:"items,omitempty"`
	Links *KafkaClusterListLinks `json:"_links,omitempty"`
}

// NewKafkaClusterListApiResource instantiates a new KafkaClusterListApiResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaClusterListApiResource() *KafkaClusterListApiResource {
	this := KafkaClusterListApiResource{}
	return &this
}

// NewKafkaClusterListApiResourceWithDefaults instantiates a new KafkaClusterListApiResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaClusterListApiResourceWithDefaults() *KafkaClusterListApiResource {
	this := KafkaClusterListApiResource{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KafkaClusterListApiResource) GetItems() []KafkaClusterApiResource {
	if o == nil {
		var ret []KafkaClusterApiResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KafkaClusterListApiResource) GetItemsOk() ([]KafkaClusterApiResource, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KafkaClusterListApiResource) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaClusterApiResource and assigns it to the Items field.
func (o *KafkaClusterListApiResource) SetItems(v []KafkaClusterApiResource) {
	o.Items = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *KafkaClusterListApiResource) GetLinks() KafkaClusterListLinks {
	if o == nil || IsNil(o.Links) {
		var ret KafkaClusterListLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaClusterListApiResource) GetLinksOk() (*KafkaClusterListLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *KafkaClusterListApiResource) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given KafkaClusterListLinks and assigns it to the Links field.
func (o *KafkaClusterListApiResource) SetLinks(v KafkaClusterListLinks) {
	o.Links = &v
}

func (o KafkaClusterListApiResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaClusterListApiResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableKafkaClusterListApiResource struct {
	value *KafkaClusterListApiResource
	isSet bool
}

func (v NullableKafkaClusterListApiResource) Get() *KafkaClusterListApiResource {
	return v.value
}

func (v *NullableKafkaClusterListApiResource) Set(val *KafkaClusterListApiResource) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaClusterListApiResource) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaClusterListApiResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaClusterListApiResource(val *KafkaClusterListApiResource) *NullableKafkaClusterListApiResource {
	return &NullableKafkaClusterListApiResource{value: val, isSet: true}
}

func (v NullableKafkaClusterListApiResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaClusterListApiResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


