/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewCapabilityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewCapabilityRequest{}

// NewCapabilityRequest struct for NewCapabilityRequest
type NewCapabilityRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	JsonMetadata NullableString `json:"jsonMetadata,omitempty"`
	Invitees []string `json:"invitees,omitempty"`
}

type _NewCapabilityRequest NewCapabilityRequest

// NewNewCapabilityRequest instantiates a new NewCapabilityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewCapabilityRequest(name string) *NewCapabilityRequest {
	this := NewCapabilityRequest{}
	this.Name = name
	return &this
}

// NewNewCapabilityRequestWithDefaults instantiates a new NewCapabilityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewCapabilityRequestWithDefaults() *NewCapabilityRequest {
	this := NewCapabilityRequest{}
	return &this
}

// GetName returns the Name field value
func (o *NewCapabilityRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewCapabilityRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewCapabilityRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewCapabilityRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewCapabilityRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *NewCapabilityRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *NewCapabilityRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *NewCapabilityRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *NewCapabilityRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetJsonMetadata returns the JsonMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewCapabilityRequest) GetJsonMetadata() string {
	if o == nil || IsNil(o.JsonMetadata.Get()) {
		var ret string
		return ret
	}
	return *o.JsonMetadata.Get()
}

// GetJsonMetadataOk returns a tuple with the JsonMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewCapabilityRequest) GetJsonMetadataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JsonMetadata.Get(), o.JsonMetadata.IsSet()
}

// HasJsonMetadata returns a boolean if a field has been set.
func (o *NewCapabilityRequest) HasJsonMetadata() bool {
	if o != nil && o.JsonMetadata.IsSet() {
		return true
	}

	return false
}

// SetJsonMetadata gets a reference to the given NullableString and assigns it to the JsonMetadata field.
func (o *NewCapabilityRequest) SetJsonMetadata(v string) {
	o.JsonMetadata.Set(&v)
}
// SetJsonMetadataNil sets the value for JsonMetadata to be an explicit nil
func (o *NewCapabilityRequest) SetJsonMetadataNil() {
	o.JsonMetadata.Set(nil)
}

// UnsetJsonMetadata ensures that no value is present for JsonMetadata, not even an explicit nil
func (o *NewCapabilityRequest) UnsetJsonMetadata() {
	o.JsonMetadata.Unset()
}

// GetInvitees returns the Invitees field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewCapabilityRequest) GetInvitees() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Invitees
}

// GetInviteesOk returns a tuple with the Invitees field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewCapabilityRequest) GetInviteesOk() ([]string, bool) {
	if o == nil || IsNil(o.Invitees) {
		return nil, false
	}
	return o.Invitees, true
}

// HasInvitees returns a boolean if a field has been set.
func (o *NewCapabilityRequest) HasInvitees() bool {
	if o != nil && !IsNil(o.Invitees) {
		return true
	}

	return false
}

// SetInvitees gets a reference to the given []string and assigns it to the Invitees field.
func (o *NewCapabilityRequest) SetInvitees(v []string) {
	o.Invitees = v
}

func (o NewCapabilityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewCapabilityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.JsonMetadata.IsSet() {
		toSerialize["jsonMetadata"] = o.JsonMetadata.Get()
	}
	if o.Invitees != nil {
		toSerialize["invitees"] = o.Invitees
	}
	return toSerialize, nil
}

func (o *NewCapabilityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewCapabilityRequest := _NewCapabilityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewCapabilityRequest)

	if err != nil {
		return err
	}

	*o = NewCapabilityRequest(varNewCapabilityRequest)

	return err
}

type NullableNewCapabilityRequest struct {
	value *NewCapabilityRequest
	isSet bool
}

func (v NullableNewCapabilityRequest) Get() *NewCapabilityRequest {
	return v.value
}

func (v *NullableNewCapabilityRequest) Set(val *NewCapabilityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNewCapabilityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNewCapabilityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewCapabilityRequest(val *NewCapabilityRequest) *NullableNewCapabilityRequest {
	return &NullableNewCapabilityRequest{value: val, isSet: true}
}

func (v NullableNewCapabilityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewCapabilityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


