/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MembershipApprovalListLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MembershipApprovalListLinks{}

// MembershipApprovalListLinks struct for MembershipApprovalListLinks
type MembershipApprovalListLinks struct {
	Self *ResourceLink `json:"self,omitempty"`
}

// NewMembershipApprovalListLinks instantiates a new MembershipApprovalListLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembershipApprovalListLinks() *MembershipApprovalListLinks {
	this := MembershipApprovalListLinks{}
	return &this
}

// NewMembershipApprovalListLinksWithDefaults instantiates a new MembershipApprovalListLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipApprovalListLinksWithDefaults() *MembershipApprovalListLinks {
	this := MembershipApprovalListLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *MembershipApprovalListLinks) GetSelf() ResourceLink {
	if o == nil || IsNil(o.Self) {
		var ret ResourceLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MembershipApprovalListLinks) GetSelfOk() (*ResourceLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *MembershipApprovalListLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given ResourceLink and assigns it to the Self field.
func (o *MembershipApprovalListLinks) SetSelf(v ResourceLink) {
	o.Self = &v
}

func (o MembershipApprovalListLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MembershipApprovalListLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableMembershipApprovalListLinks struct {
	value *MembershipApprovalListLinks
	isSet bool
}

func (v NullableMembershipApprovalListLinks) Get() *MembershipApprovalListLinks {
	return v.value
}

func (v *NullableMembershipApprovalListLinks) Set(val *MembershipApprovalListLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableMembershipApprovalListLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableMembershipApprovalListLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembershipApprovalListLinks(val *MembershipApprovalListLinks) *NullableMembershipApprovalListLinks {
	return &NullableMembershipApprovalListLinks{value: val, isSet: true}
}

func (v NullableMembershipApprovalListLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembershipApprovalListLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


