/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidateSelfServiceJsonSchemaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateSelfServiceJsonSchemaRequest{}

// ValidateSelfServiceJsonSchemaRequest struct for ValidateSelfServiceJsonSchemaRequest
type ValidateSelfServiceJsonSchemaRequest struct {
	Schema map[string]JsonNode `json:"schema"`
}

type _ValidateSelfServiceJsonSchemaRequest ValidateSelfServiceJsonSchemaRequest

// NewValidateSelfServiceJsonSchemaRequest instantiates a new ValidateSelfServiceJsonSchemaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateSelfServiceJsonSchemaRequest(schema map[string]JsonNode) *ValidateSelfServiceJsonSchemaRequest {
	this := ValidateSelfServiceJsonSchemaRequest{}
	this.Schema = schema
	return &this
}

// NewValidateSelfServiceJsonSchemaRequestWithDefaults instantiates a new ValidateSelfServiceJsonSchemaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateSelfServiceJsonSchemaRequestWithDefaults() *ValidateSelfServiceJsonSchemaRequest {
	this := ValidateSelfServiceJsonSchemaRequest{}
	return &this
}

// GetSchema returns the Schema field value
func (o *ValidateSelfServiceJsonSchemaRequest) GetSchema() map[string]JsonNode {
	if o == nil {
		var ret map[string]JsonNode
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *ValidateSelfServiceJsonSchemaRequest) GetSchemaOk() (*map[string]JsonNode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *ValidateSelfServiceJsonSchemaRequest) SetSchema(v map[string]JsonNode) {
	o.Schema = v
}

func (o ValidateSelfServiceJsonSchemaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateSelfServiceJsonSchemaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schema"] = o.Schema
	return toSerialize, nil
}

func (o *ValidateSelfServiceJsonSchemaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schema",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateSelfServiceJsonSchemaRequest := _ValidateSelfServiceJsonSchemaRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateSelfServiceJsonSchemaRequest)

	if err != nil {
		return err
	}

	*o = ValidateSelfServiceJsonSchemaRequest(varValidateSelfServiceJsonSchemaRequest)

	return err
}

type NullableValidateSelfServiceJsonSchemaRequest struct {
	value *ValidateSelfServiceJsonSchemaRequest
	isSet bool
}

func (v NullableValidateSelfServiceJsonSchemaRequest) Get() *ValidateSelfServiceJsonSchemaRequest {
	return v.value
}

func (v *NullableValidateSelfServiceJsonSchemaRequest) Set(val *ValidateSelfServiceJsonSchemaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateSelfServiceJsonSchemaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateSelfServiceJsonSchemaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateSelfServiceJsonSchemaRequest(val *ValidateSelfServiceJsonSchemaRequest) *NullableValidateSelfServiceJsonSchemaRequest {
	return &NullableValidateSelfServiceJsonSchemaRequest{value: val, isSet: true}
}

func (v NullableValidateSelfServiceJsonSchemaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateSelfServiceJsonSchemaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


