/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapabilityListItemApiResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityListItemApiResource{}

// CapabilityListItemApiResource struct for CapabilityListItemApiResource
type CapabilityListItemApiResource struct {
	Id NullableString `json:"id,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Status NullableString `json:"status,omitempty"`
	Description NullableString `json:"description,omitempty"`
	JsonMetadata NullableString `json:"jsonMetadata,omitempty"`
	AwsAccountId NullableString `json:"awsAccountId,omitempty"`
	Links *CapabilityListItemLinks `json:"_links,omitempty"`
}

// NewCapabilityListItemApiResource instantiates a new CapabilityListItemApiResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityListItemApiResource() *CapabilityListItemApiResource {
	this := CapabilityListItemApiResource{}
	return &this
}

// NewCapabilityListItemApiResourceWithDefaults instantiates a new CapabilityListItemApiResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityListItemApiResourceWithDefaults() *CapabilityListItemApiResource {
	this := CapabilityListItemApiResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *CapabilityListItemApiResource) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *CapabilityListItemApiResource) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CapabilityListItemApiResource) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CapabilityListItemApiResource) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetName() {
	o.Name.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *CapabilityListItemApiResource) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *CapabilityListItemApiResource) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetStatus() {
	o.Status.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CapabilityListItemApiResource) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CapabilityListItemApiResource) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetDescription() {
	o.Description.Unset()
}

// GetJsonMetadata returns the JsonMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetJsonMetadata() string {
	if o == nil || IsNil(o.JsonMetadata.Get()) {
		var ret string
		return ret
	}
	return *o.JsonMetadata.Get()
}

// GetJsonMetadataOk returns a tuple with the JsonMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetJsonMetadataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JsonMetadata.Get(), o.JsonMetadata.IsSet()
}

// HasJsonMetadata returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasJsonMetadata() bool {
	if o != nil && o.JsonMetadata.IsSet() {
		return true
	}

	return false
}

// SetJsonMetadata gets a reference to the given NullableString and assigns it to the JsonMetadata field.
func (o *CapabilityListItemApiResource) SetJsonMetadata(v string) {
	o.JsonMetadata.Set(&v)
}
// SetJsonMetadataNil sets the value for JsonMetadata to be an explicit nil
func (o *CapabilityListItemApiResource) SetJsonMetadataNil() {
	o.JsonMetadata.Set(nil)
}

// UnsetJsonMetadata ensures that no value is present for JsonMetadata, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetJsonMetadata() {
	o.JsonMetadata.Unset()
}

// GetAwsAccountId returns the AwsAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityListItemApiResource) GetAwsAccountId() string {
	if o == nil || IsNil(o.AwsAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.AwsAccountId.Get()
}

// GetAwsAccountIdOk returns a tuple with the AwsAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityListItemApiResource) GetAwsAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsAccountId.Get(), o.AwsAccountId.IsSet()
}

// HasAwsAccountId returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasAwsAccountId() bool {
	if o != nil && o.AwsAccountId.IsSet() {
		return true
	}

	return false
}

// SetAwsAccountId gets a reference to the given NullableString and assigns it to the AwsAccountId field.
func (o *CapabilityListItemApiResource) SetAwsAccountId(v string) {
	o.AwsAccountId.Set(&v)
}
// SetAwsAccountIdNil sets the value for AwsAccountId to be an explicit nil
func (o *CapabilityListItemApiResource) SetAwsAccountIdNil() {
	o.AwsAccountId.Set(nil)
}

// UnsetAwsAccountId ensures that no value is present for AwsAccountId, not even an explicit nil
func (o *CapabilityListItemApiResource) UnsetAwsAccountId() {
	o.AwsAccountId.Unset()
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CapabilityListItemApiResource) GetLinks() CapabilityListItemLinks {
	if o == nil || IsNil(o.Links) {
		var ret CapabilityListItemLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityListItemApiResource) GetLinksOk() (*CapabilityListItemLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CapabilityListItemApiResource) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CapabilityListItemLinks and assigns it to the Links field.
func (o *CapabilityListItemApiResource) SetLinks(v CapabilityListItemLinks) {
	o.Links = &v
}

func (o CapabilityListItemApiResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityListItemApiResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.JsonMetadata.IsSet() {
		toSerialize["jsonMetadata"] = o.JsonMetadata.Get()
	}
	if o.AwsAccountId.IsSet() {
		toSerialize["awsAccountId"] = o.AwsAccountId.Get()
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCapabilityListItemApiResource struct {
	value *CapabilityListItemApiResource
	isSet bool
}

func (v NullableCapabilityListItemApiResource) Get() *CapabilityListItemApiResource {
	return v.value
}

func (v *NullableCapabilityListItemApiResource) Set(val *CapabilityListItemApiResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityListItemApiResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityListItemApiResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityListItemApiResource(val *CapabilityListItemApiResource) *NullableCapabilityListItemApiResource {
	return &NullableCapabilityListItemApiResource{value: val, isSet: true}
}

func (v NullableCapabilityListItemApiResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityListItemApiResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


