/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CapabilityMembersApiResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilityMembersApiResource{}

// CapabilityMembersApiResource struct for CapabilityMembersApiResource
type CapabilityMembersApiResource struct {
	Items []MemberApiResource `json:"items,omitempty"`
	Links *CapabilityMembersLinks `json:"_links,omitempty"`
}

// NewCapabilityMembersApiResource instantiates a new CapabilityMembersApiResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityMembersApiResource() *CapabilityMembersApiResource {
	this := CapabilityMembersApiResource{}
	return &this
}

// NewCapabilityMembersApiResourceWithDefaults instantiates a new CapabilityMembersApiResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityMembersApiResourceWithDefaults() *CapabilityMembersApiResource {
	this := CapabilityMembersApiResource{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CapabilityMembersApiResource) GetItems() []MemberApiResource {
	if o == nil {
		var ret []MemberApiResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CapabilityMembersApiResource) GetItemsOk() ([]MemberApiResource, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CapabilityMembersApiResource) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []MemberApiResource and assigns it to the Items field.
func (o *CapabilityMembersApiResource) SetItems(v []MemberApiResource) {
	o.Items = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CapabilityMembersApiResource) GetLinks() CapabilityMembersLinks {
	if o == nil || IsNil(o.Links) {
		var ret CapabilityMembersLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilityMembersApiResource) GetLinksOk() (*CapabilityMembersLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CapabilityMembersApiResource) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given CapabilityMembersLinks and assigns it to the Links field.
func (o *CapabilityMembersApiResource) SetLinks(v CapabilityMembersLinks) {
	o.Links = &v
}

func (o CapabilityMembersApiResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilityMembersApiResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCapabilityMembersApiResource struct {
	value *CapabilityMembersApiResource
	isSet bool
}

func (v NullableCapabilityMembersApiResource) Get() *CapabilityMembersApiResource {
	return v.value
}

func (v *NullableCapabilityMembersApiResource) Set(val *CapabilityMembersApiResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityMembersApiResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityMembersApiResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityMembersApiResource(val *CapabilityMembersApiResource) *NullableCapabilityMembersApiResource {
	return &NullableCapabilityMembersApiResource{value: val, isSet: true}
}

func (v NullableCapabilityMembersApiResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityMembersApiResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


