/*
SelfService API

SelfService API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResourceActionLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceActionLink{}

// ResourceActionLink struct for ResourceActionLink
type ResourceActionLink struct {
	Href NullableString `json:"href,omitempty"`
	Method NullableString `json:"method,omitempty"`
}

// NewResourceActionLink instantiates a new ResourceActionLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceActionLink() *ResourceActionLink {
	this := ResourceActionLink{}
	return &this
}

// NewResourceActionLinkWithDefaults instantiates a new ResourceActionLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceActionLinkWithDefaults() *ResourceActionLink {
	this := ResourceActionLink{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceActionLink) GetHref() string {
	if o == nil || IsNil(o.Href.Get()) {
		var ret string
		return ret
	}
	return *o.Href.Get()
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceActionLink) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Href.Get(), o.Href.IsSet()
}

// HasHref returns a boolean if a field has been set.
func (o *ResourceActionLink) HasHref() bool {
	if o != nil && o.Href.IsSet() {
		return true
	}

	return false
}

// SetHref gets a reference to the given NullableString and assigns it to the Href field.
func (o *ResourceActionLink) SetHref(v string) {
	o.Href.Set(&v)
}
// SetHrefNil sets the value for Href to be an explicit nil
func (o *ResourceActionLink) SetHrefNil() {
	o.Href.Set(nil)
}

// UnsetHref ensures that no value is present for Href, not even an explicit nil
func (o *ResourceActionLink) UnsetHref() {
	o.Href.Unset()
}

// GetMethod returns the Method field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResourceActionLink) GetMethod() string {
	if o == nil || IsNil(o.Method.Get()) {
		var ret string
		return ret
	}
	return *o.Method.Get()
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResourceActionLink) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Method.Get(), o.Method.IsSet()
}

// HasMethod returns a boolean if a field has been set.
func (o *ResourceActionLink) HasMethod() bool {
	if o != nil && o.Method.IsSet() {
		return true
	}

	return false
}

// SetMethod gets a reference to the given NullableString and assigns it to the Method field.
func (o *ResourceActionLink) SetMethod(v string) {
	o.Method.Set(&v)
}
// SetMethodNil sets the value for Method to be an explicit nil
func (o *ResourceActionLink) SetMethodNil() {
	o.Method.Set(nil)
}

// UnsetMethod ensures that no value is present for Method, not even an explicit nil
func (o *ResourceActionLink) UnsetMethod() {
	o.Method.Unset()
}

func (o ResourceActionLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceActionLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Href.IsSet() {
		toSerialize["href"] = o.Href.Get()
	}
	if o.Method.IsSet() {
		toSerialize["method"] = o.Method.Get()
	}
	return toSerialize, nil
}

type NullableResourceActionLink struct {
	value *ResourceActionLink
	isSet bool
}

func (v NullableResourceActionLink) Get() *ResourceActionLink {
	return v.value
}

func (v *NullableResourceActionLink) Set(val *ResourceActionLink) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceActionLink) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceActionLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceActionLink(val *ResourceActionLink) *NullableResourceActionLink {
	return &NullableResourceActionLink{value: val, isSet: true}
}

func (v NullableResourceActionLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceActionLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


